version: '3.4'

services:
  ci-build:
    image: microsoft/dotnet:2.2-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./GrandNode.sln && dotnet publish ./GrandNode.sln -c Release -o ./obj/Docker/publish"
